#!/bin/sh

case $BLOCK_BUTTON in
	1) pkill -RTMIN+4 dwmblocks ;;
esac

# Wi-Fi
if [ "$(cat /sys/class/net/w*/operstate 2>/dev/null)" = 'up' ] ; then
	wifi_strength=$(awk '/^\s*w/ { print int($3 * 100 / 70) }' /proc/net/wireless)
	wifi_status="Wi-Fi: ON ($wifi_strength%)"
else
	wifi_status="Wi-Fi: OFF"
fi

# Ethernet
if [ "$(cat /sys/class/net/e*/operstate 2>/dev/null)" = 'up' ]; then
	ethernet_status="Ethernet: Connected"
else
	ethernet_status="Ethernet: OFF"
fi

printf "%s - %s\n" "$wifi_status" "$ethernet_status"